CC=g++
CFLAGS=-g -std=c++17 -c -Wall
LINKERFLAGS=
SOURCES=compiler.cpp parser.cpp lexer.cpp cst.cpp ast.cpp semantic.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=compiler

all: $(SOURCES) $(EXECUTABLE)
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LINKERFLAGS) $(OBJECTS) -o $@

.cpp.o: 
	$(CC) $(CFLAGS) $< -o $@
	
run: $(EXECUTABLE)
	./$(EXECUTABLE)

clean:
	rm -rf *.o $(EXECUTABLE)
