CC=g++ 
CFLAGS=-std=c++17 -c -Wall
LINKERFLAGS=
SOURCES=compiler.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=compiler

all: $(SOURCES) $(EXECUTABLE)
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LINKERFLAGS) $(OBJECTS) -o $@

.cpp: 
	$(CC) $(CFLAGS) $< -o $@
run: $(EXECUTABLE)
	./$(EXECUTABLE)

clean:
	rm -rf *.o $(EXECUTABLE)

